services:
  payload:
    image: tessio94/boulder-payloadcms:latest
    environment:
      DATABASE_URL_FILE: /run/secrets/db_url
      PAYLOAD_SECRET_FILE: /run/secrets/payload_secret
    secrets:
      - db_url
      - payload_secret
    volumes:
      - payload-media:/app/media
      - static-assets:/app/.next/static
    expose:
      - "3000"
    depends_on:
      - db-boulder

  nginx:
    image: tessio94/boulder-nginx:latest
    ports:
      - "80:80"
    volumes:
      - payload-media:/usr/share/nginx/html/media:ro
      - static-assets:/usr/share/nginx/html/_next/static:ro
    depends_on:
      - payload

  db-boulder:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
    secrets:
      - postgres_passwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300

volumes:
  pgdata:
  payload-media:
  static-assets:

secrets:
  db_url:
    external: true
  payload_secret:
    external: true
  postgres_passwd:
    external: true
