# Dockerfile.nginx
FROM nginx:alpine

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# These paths will be mounted from volumes
RUN mkdir -p /usr/share/nginx/html/media /usr/share/nginx/html/_next/static

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]