# version: "3"

# services:
#   payload:
#     image: payload-boulder
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       # - migrate
#       - db-boulder
#     env_file:
#       - .env

#   db-boulder:
#     restart: always
#     image: postgres:latest
#     volumes:
#       - pgdata:/var/lib/postgresql
#     ports:
#       - "5432:5432"
#     env_file:
#       - .env

# volumes:
#   pgdata:
#   node_modules:
services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media
    ports:
      - "3000:3000"
    depends_on:
      - db-boulder

  db-boulder:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dellas113
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
