services:
  payload:
    image: payload-boulder
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./media:/app/media
    ports:
      - "3000:3000"
    depends_on:
      - db-boulder

  db-boulder:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dellas113
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
