/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["en", "de"]);
export const enum_gyms_working_hours_days = pgEnum(
  "enum_gyms_working_hours_days",
  ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
);
export const enum_categories_gender = pgEnum("enum_categories_gender", [
  "male",
  "female",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    backgroundColor: varchar("background_color"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const events = pgTable(
  "events",
  {
    id: serial("id").primaryKey(),
    _order: varchar("_order"),
    from: timestamp("from", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    until: timestamp("until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    gym: integer("gym_id")
      .notNull()
      .references(() => gyms.id, {
        onDelete: "set null",
      }),
    location: varchar("location"),
    heroImage: integer("hero_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    cardImage: integer("card_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    timeframe_start: timestamp("timeframe_start", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    timeframe_end: timestamp("timeframe_end", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    registration_start: timestamp("registration_start", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    registration_end: timestamp("registration_end", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    slug: varchar("slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("events__order_idx").on(columns._order),
    index("events_gym_idx").on(columns.gym),
    index("events_hero_image_idx").on(columns.heroImage),
    index("events_card_image_idx").on(columns.cardImage),
    uniqueIndex("events_slug_idx").on(columns.slug),
    index("events_updated_at_idx").on(columns.updatedAt),
    index("events_created_at_idx").on(columns.createdAt),
  ],
);

export const events_locales = pgTable(
  "events_locales",
  {
    title: varchar("title").notNull(),
    description: varchar("description"),
    content: jsonb("content").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("events_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events_rels = pgTable(
  "events_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("events_rels_order_idx").on(columns.order),
    index("events_rels_parent_idx").on(columns.parent),
    index("events_rels_path_idx").on(columns.path),
    index("events_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [events.id],
      name: "events_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "events_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const gyms_working_hours_days = pgTable(
  "gyms_working_hours_days",
  {
    order: integer("order").notNull(),
    parent: varchar("parent_id").notNull(),
    value: enum_gyms_working_hours_days("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("gyms_working_hours_days_order_idx").on(columns.order),
    index("gyms_working_hours_days_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [gyms_working_hours.id],
      name: "gyms_working_hours_days_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const gyms_working_hours = pgTable(
  "gyms_working_hours",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    from: numeric("from", { mode: "number" }).notNull(),
    to: numeric("to", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("gyms_working_hours_order_idx").on(columns._order),
    index("gyms_working_hours_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [gyms.id],
      name: "gyms_working_hours_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const gyms = pgTable(
  "gyms",
  {
    id: serial("id").primaryKey(),
    _order: varchar("_order"),
    name: varchar("name").notNull(),
    heroImage: integer("hero_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    location: varchar("location").notNull(),
    phone: varchar("phone"),
    email: varchar("email"),
    website: varchar("website"),
    slug: varchar("slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("gyms__order_idx").on(columns._order),
    index("gyms_hero_image_idx").on(columns.heroImage),
    uniqueIndex("gyms_slug_idx").on(columns.slug),
    index("gyms_updated_at_idx").on(columns.updatedAt),
    index("gyms_created_at_idx").on(columns.createdAt),
  ],
);

export const gyms_locales = pgTable(
  "gyms_locales",
  {
    information: varchar("information").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("gyms_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [gyms.id],
      name: "gyms_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const gyms_rels = pgTable(
  "gyms_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("gyms_rels_order_idx").on(columns.order),
    index("gyms_rels_parent_idx").on(columns.parent),
    index("gyms_rels_path_idx").on(columns.path),
    index("gyms_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [gyms.id],
      name: "gyms_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "gyms_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const members_sessions = pgTable(
  "members_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("members_sessions_order_idx").on(columns._order),
    index("members_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [members.id],
      name: "members_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const members = pgTable(
  "members",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name").notNull(),
    lastName: varchar("last_name").notNull(),
    userName: varchar("user_name").notNull(),
    phoneNumber: varchar("phone_number"),
    termsAcceptedAt: timestamp("terms_accepted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    fullName: varchar("full_name"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("members_updated_at_idx").on(columns.updatedAt),
    index("members_created_at_idx").on(columns.createdAt),
    uniqueIndex("members_email_idx").on(columns.email),
  ],
);

export const members_rels = pgTable(
  "members_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "event-registrationsID": integer("event_registrations_id"),
  },
  (columns) => [
    index("members_rels_order_idx").on(columns.order),
    index("members_rels_parent_idx").on(columns.parent),
    index("members_rels_path_idx").on(columns.path),
    index("members_rels_event_registrations_id_idx").on(
      columns["event-registrationsID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [members.id],
      name: "members_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["event-registrationsID"]],
      foreignColumns: [event_registrations.id],
      name: "members_rels_event_registrations_fk",
    }).onDelete("cascade"),
  ],
);

export const results = pgTable(
  "results",
  {
    id: serial("id").primaryKey(),
    member: integer("member_id")
      .notNull()
      .references(() => members.id, {
        onDelete: "set null",
      }),
    event: integer("event_id")
      .notNull()
      .references(() => events.id, {
        onDelete: "set null",
      }),
    stage: integer("stage_id")
      .notNull()
      .references(() => stages.id, {
        onDelete: "set null",
      }),
    category: integer("category_id")
      .notNull()
      .references(() => categories.id, {
        onDelete: "set null",
      }),
    goal: varchar("goal").notNull(),
    points: numeric("points", { mode: "number" }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("results_member_idx").on(columns.member),
    index("results_event_idx").on(columns.event),
    index("results_stage_idx").on(columns.stage),
    index("results_category_idx").on(columns.category),
    index("results_updated_at_idx").on(columns.updatedAt),
    index("results_created_at_idx").on(columns.createdAt),
    uniqueIndex("member_event_stage_idx").on(
      columns.member,
      columns.event,
      columns.stage,
    ),
  ],
);

export const stages_goals = pgTable(
  "stages_goals",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    name: varchar("name").notNull(),
    baseScore: numeric("base_score", { mode: "number" }).notNull(),
    coefficient: numeric("coefficient", { mode: "number" }).default(1),
  },
  (columns) => [
    index("stages_goals_order_idx").on(columns._order),
    index("stages_goals_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [stages.id],
      name: "stages_goals_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const stages = pgTable(
  "stages",
  {
    id: serial("id").primaryKey(),
    event: integer("event_id")
      .notNull()
      .references(() => events.id, {
        onDelete: "set null",
      }),
    name: varchar("name").notNull(),
    location: varchar("location"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("stages_event_idx").on(columns.event),
    index("stages_image_idx").on(columns.image),
    index("stages_updated_at_idx").on(columns.updatedAt),
    index("stages_created_at_idx").on(columns.createdAt),
  ],
);

export const event_registrations = pgTable(
  "event_registrations",
  {
    id: serial("id").primaryKey(),
    event: integer("event_id")
      .notNull()
      .references(() => events.id, {
        onDelete: "set null",
      }),
    member: integer("member_id")
      .notNull()
      .references(() => members.id, {
        onDelete: "set null",
      }),
    category: integer("category_id")
      .notNull()
      .references(() => categories.id, {
        onDelete: "set null",
      }),
    order: numeric("order", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("event_registrations_event_idx").on(columns.event),
    index("event_registrations_member_idx").on(columns.member),
    index("event_registrations_category_idx").on(columns.category),
    index("event_registrations_updated_at_idx").on(columns.updatedAt),
    index("event_registrations_created_at_idx").on(columns.createdAt),
    uniqueIndex("member_event_idx").on(columns.member, columns.event),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    event: integer("event_id")
      .notNull()
      .references(() => events.id, {
        onDelete: "set null",
      }),
    name: varchar("name").notNull(),
    ageFrom: numeric("age_from", { mode: "number" }),
    ageTo: numeric("age_to", { mode: "number" }),
    gender: enum_categories_gender("gender"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("categories_event_idx").on(columns.event),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const categories_rels = pgTable(
  "categories_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "event-registrationsID": integer("event_registrations_id"),
  },
  (columns) => [
    index("categories_rels_order_idx").on(columns.order),
    index("categories_rels_parent_idx").on(columns.parent),
    index("categories_rels_path_idx").on(columns.path),
    index("categories_rels_event_registrations_id_idx").on(
      columns["event-registrationsID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [categories.id],
      name: "categories_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["event-registrationsID"]],
      foreignColumns: [event_registrations.id],
      name: "categories_rels_event_registrations_fk",
    }).onDelete("cascade"),
  ],
);

export const news = pgTable(
  "news",
  {
    id: serial("id").primaryKey(),
    _order: varchar("_order"),
    newsImage: integer("news_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    slug: varchar("slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("news__order_idx").on(columns._order),
    index("news_news_image_idx").on(columns.newsImage),
    uniqueIndex("news_slug_idx").on(columns.slug),
    index("news_updated_at_idx").on(columns.updatedAt),
    index("news_created_at_idx").on(columns.createdAt),
  ],
);

export const news_locales = pgTable(
  "news_locales",
  {
    title: varchar("title").notNull(),
    intro: varchar("intro"),
    content: jsonb("content").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("news_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [news.id],
      name: "news_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const news_rels = pgTable(
  "news_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("news_rels_order_idx").on(columns.order),
    index("news_rels_parent_idx").on(columns.parent),
    index("news_rels_path_idx").on(columns.path),
    index("news_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [news.id],
      name: "news_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "news_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    eventsID: integer("events_id"),
    gymsID: integer("gyms_id"),
    membersID: integer("members_id"),
    resultsID: integer("results_id"),
    stagesID: integer("stages_id"),
    "event-registrationsID": integer("event_registrations_id"),
    categoriesID: integer("categories_id"),
    newsID: integer("news_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
    index("payload_locked_documents_rels_gyms_id_idx").on(columns.gymsID),
    index("payload_locked_documents_rels_members_id_idx").on(columns.membersID),
    index("payload_locked_documents_rels_results_id_idx").on(columns.resultsID),
    index("payload_locked_documents_rels_stages_id_idx").on(columns.stagesID),
    index("payload_locked_documents_rels_event_registrations_id_idx").on(
      columns["event-registrationsID"],
    ),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_news_id_idx").on(columns.newsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "payload_locked_documents_rels_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["gymsID"]],
      foreignColumns: [gyms.id],
      name: "payload_locked_documents_rels_gyms_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["membersID"]],
      foreignColumns: [members.id],
      name: "payload_locked_documents_rels_members_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["resultsID"]],
      foreignColumns: [results.id],
      name: "payload_locked_documents_rels_results_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["stagesID"]],
      foreignColumns: [stages.id],
      name: "payload_locked_documents_rels_stages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["event-registrationsID"]],
      foreignColumns: [event_registrations.id],
      name: "payload_locked_documents_rels_event_registrations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["newsID"]],
      foreignColumns: [news.id],
      name: "payload_locked_documents_rels_news_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    membersID: integer("members_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    index("payload_preferences_rels_members_id_idx").on(columns.membersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["membersID"]],
      foreignColumns: [members.id],
      name: "payload_preferences_rels_members_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_events_locales = relations(
  events_locales,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_locales._parentID],
      references: [events.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_events_rels = relations(events_rels, ({ one }) => ({
  parent: one(events, {
    fields: [events_rels.parent],
    references: [events.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [events_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_events = relations(events, ({ one, many }) => ({
  gym: one(gyms, {
    fields: [events.gym],
    references: [gyms.id],
    relationName: "gym",
  }),
  heroImage: one(media, {
    fields: [events.heroImage],
    references: [media.id],
    relationName: "heroImage",
  }),
  cardImage: one(media, {
    fields: [events.cardImage],
    references: [media.id],
    relationName: "cardImage",
  }),
  _locales: many(events_locales, {
    relationName: "_locales",
  }),
  _rels: many(events_rels, {
    relationName: "_rels",
  }),
}));
export const relations_gyms_working_hours_days = relations(
  gyms_working_hours_days,
  ({ one }) => ({
    parent: one(gyms_working_hours, {
      fields: [gyms_working_hours_days.parent],
      references: [gyms_working_hours.id],
      relationName: "days",
    }),
  }),
);
export const relations_gyms_working_hours = relations(
  gyms_working_hours,
  ({ one, many }) => ({
    _parentID: one(gyms, {
      fields: [gyms_working_hours._parentID],
      references: [gyms.id],
      relationName: "workingHours",
    }),
    days: many(gyms_working_hours_days, {
      relationName: "days",
    }),
  }),
);
export const relations_gyms_locales = relations(gyms_locales, ({ one }) => ({
  _parentID: one(gyms, {
    fields: [gyms_locales._parentID],
    references: [gyms.id],
    relationName: "_locales",
  }),
}));
export const relations_gyms_rels = relations(gyms_rels, ({ one }) => ({
  parent: one(gyms, {
    fields: [gyms_rels.parent],
    references: [gyms.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [gyms_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_gyms = relations(gyms, ({ one, many }) => ({
  heroImage: one(media, {
    fields: [gyms.heroImage],
    references: [media.id],
    relationName: "heroImage",
  }),
  workingHours: many(gyms_working_hours, {
    relationName: "workingHours",
  }),
  _locales: many(gyms_locales, {
    relationName: "_locales",
  }),
  _rels: many(gyms_rels, {
    relationName: "_rels",
  }),
}));
export const relations_members_sessions = relations(
  members_sessions,
  ({ one }) => ({
    _parentID: one(members, {
      fields: [members_sessions._parentID],
      references: [members.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_members_rels = relations(members_rels, ({ one }) => ({
  parent: one(members, {
    fields: [members_rels.parent],
    references: [members.id],
    relationName: "_rels",
  }),
  "event-registrationsID": one(event_registrations, {
    fields: [members_rels["event-registrationsID"]],
    references: [event_registrations.id],
    relationName: "event-registrations",
  }),
}));
export const relations_members = relations(members, ({ many }) => ({
  sessions: many(members_sessions, {
    relationName: "sessions",
  }),
  _rels: many(members_rels, {
    relationName: "_rels",
  }),
}));
export const relations_results = relations(results, ({ one }) => ({
  member: one(members, {
    fields: [results.member],
    references: [members.id],
    relationName: "member",
  }),
  event: one(events, {
    fields: [results.event],
    references: [events.id],
    relationName: "event",
  }),
  stage: one(stages, {
    fields: [results.stage],
    references: [stages.id],
    relationName: "stage",
  }),
  category: one(categories, {
    fields: [results.category],
    references: [categories.id],
    relationName: "category",
  }),
}));
export const relations_stages_goals = relations(stages_goals, ({ one }) => ({
  _parentID: one(stages, {
    fields: [stages_goals._parentID],
    references: [stages.id],
    relationName: "goals",
  }),
}));
export const relations_stages = relations(stages, ({ one, many }) => ({
  event: one(events, {
    fields: [stages.event],
    references: [events.id],
    relationName: "event",
  }),
  image: one(media, {
    fields: [stages.image],
    references: [media.id],
    relationName: "image",
  }),
  goals: many(stages_goals, {
    relationName: "goals",
  }),
}));
export const relations_event_registrations = relations(
  event_registrations,
  ({ one }) => ({
    event: one(events, {
      fields: [event_registrations.event],
      references: [events.id],
      relationName: "event",
    }),
    member: one(members, {
      fields: [event_registrations.member],
      references: [members.id],
      relationName: "member",
    }),
    category: one(categories, {
      fields: [event_registrations.category],
      references: [categories.id],
      relationName: "category",
    }),
  }),
);
export const relations_categories_rels = relations(
  categories_rels,
  ({ one }) => ({
    parent: one(categories, {
      fields: [categories_rels.parent],
      references: [categories.id],
      relationName: "_rels",
    }),
    "event-registrationsID": one(event_registrations, {
      fields: [categories_rels["event-registrationsID"]],
      references: [event_registrations.id],
      relationName: "event-registrations",
    }),
  }),
);
export const relations_categories = relations(categories, ({ one, many }) => ({
  event: one(events, {
    fields: [categories.event],
    references: [events.id],
    relationName: "event",
  }),
  _rels: many(categories_rels, {
    relationName: "_rels",
  }),
}));
export const relations_news_locales = relations(news_locales, ({ one }) => ({
  _parentID: one(news, {
    fields: [news_locales._parentID],
    references: [news.id],
    relationName: "_locales",
  }),
}));
export const relations_news_rels = relations(news_rels, ({ one }) => ({
  parent: one(news, {
    fields: [news_rels.parent],
    references: [news.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [news_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_news = relations(news, ({ one, many }) => ({
  newsImage: one(media, {
    fields: [news.newsImage],
    references: [media.id],
    relationName: "newsImage",
  }),
  _locales: many(news_locales, {
    relationName: "_locales",
  }),
  _rels: many(news_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: "events",
    }),
    gymsID: one(gyms, {
      fields: [payload_locked_documents_rels.gymsID],
      references: [gyms.id],
      relationName: "gyms",
    }),
    membersID: one(members, {
      fields: [payload_locked_documents_rels.membersID],
      references: [members.id],
      relationName: "members",
    }),
    resultsID: one(results, {
      fields: [payload_locked_documents_rels.resultsID],
      references: [results.id],
      relationName: "results",
    }),
    stagesID: one(stages, {
      fields: [payload_locked_documents_rels.stagesID],
      references: [stages.id],
      relationName: "stages",
    }),
    "event-registrationsID": one(event_registrations, {
      fields: [payload_locked_documents_rels["event-registrationsID"]],
      references: [event_registrations.id],
      relationName: "event-registrations",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    newsID: one(news, {
      fields: [payload_locked_documents_rels.newsID],
      references: [news.id],
      relationName: "news",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    membersID: one(members, {
      fields: [payload_preferences_rels.membersID],
      references: [members.id],
      relationName: "members",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_gyms_working_hours_days: typeof enum_gyms_working_hours_days;
  enum_categories_gender: typeof enum_categories_gender;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  events: typeof events;
  events_locales: typeof events_locales;
  events_rels: typeof events_rels;
  gyms_working_hours_days: typeof gyms_working_hours_days;
  gyms_working_hours: typeof gyms_working_hours;
  gyms: typeof gyms;
  gyms_locales: typeof gyms_locales;
  gyms_rels: typeof gyms_rels;
  members_sessions: typeof members_sessions;
  members: typeof members;
  members_rels: typeof members_rels;
  results: typeof results;
  stages_goals: typeof stages_goals;
  stages: typeof stages;
  event_registrations: typeof event_registrations;
  categories: typeof categories;
  categories_rels: typeof categories_rels;
  news: typeof news;
  news_locales: typeof news_locales;
  news_rels: typeof news_rels;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_events_locales: typeof relations_events_locales;
  relations_events_rels: typeof relations_events_rels;
  relations_events: typeof relations_events;
  relations_gyms_working_hours_days: typeof relations_gyms_working_hours_days;
  relations_gyms_working_hours: typeof relations_gyms_working_hours;
  relations_gyms_locales: typeof relations_gyms_locales;
  relations_gyms_rels: typeof relations_gyms_rels;
  relations_gyms: typeof relations_gyms;
  relations_members_sessions: typeof relations_members_sessions;
  relations_members_rels: typeof relations_members_rels;
  relations_members: typeof relations_members;
  relations_results: typeof relations_results;
  relations_stages_goals: typeof relations_stages_goals;
  relations_stages: typeof relations_stages;
  relations_event_registrations: typeof relations_event_registrations;
  relations_categories_rels: typeof relations_categories_rels;
  relations_categories: typeof relations_categories;
  relations_news_locales: typeof relations_news_locales;
  relations_news_rels: typeof relations_news_rels;
  relations_news: typeof relations_news;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
